injectWorkspacePackages: true

packages:
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'

minimumReleaseAgeExclude:
  - '@vitrify/*'
  - vitrify
  - unocss-preset-quasar
  - '@simsustech/*'
  - '@vue/*'
  - vue-tsc
  - unocss
  - '@unocss/*'
  - '@quasar/*'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
