// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qBtnToggleDefaults = {
  name: '',
  modelValue: '',
  options: [] as unknown[],
  color: '',
  textColor: '',
  toggleColor: 'primary',
  toggleTextColor: '',
  spread: false,
  outline: false,
  flat: false,
  unelevated: false,
  rounded: false,
  push: false,
  glossy: false,
  size: '',
  padding: '',
  noCaps: false,
  noWrap: false,
  ripple: true,
  dense: false,
  readonly: false,
  disable: false,
  stack: false,
  stretch: false,
  clearable: false,
} as const

export const qBtnToggleSchema: PropSchema[] = [
  { key: 'name', type: 'string', default: '' },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'options', type: 'array', default: [] },
  { key: 'color', type: 'string', default: '' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'toggleColor', type: 'string', default: 'primary' },
  { key: 'toggleTextColor', type: 'string', default: '' },
  { key: 'spread', type: 'boolean', default: false },
  { key: 'outline', type: 'boolean', default: false },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'unelevated', type: 'boolean', default: false },
  { key: 'rounded', type: 'boolean', default: false },
  { key: 'push', type: 'boolean', default: false },
  { key: 'glossy', type: 'boolean', default: false },
  { key: 'size', type: 'string', default: '' },
  { key: 'padding', type: 'string', default: '' },
  { key: 'noCaps', type: 'boolean', default: false },
  { key: 'noWrap', type: 'boolean', default: false },
  { key: 'ripple', type: 'string', default: true },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'readonly', type: 'boolean', default: false },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'stack', type: 'boolean', default: false },
  { key: 'stretch', type: 'boolean', default: false },
  { key: 'clearable', type: 'boolean', default: false },
]
