// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qBtnDefaults = {
  size: '',
  type: 'button',
  to: '',
  replace: false,
  href: '',
  target: '',
  label: '',
  icon: '',
  iconRight: '',
  outline: false,
  flat: false,
  unelevated: false,
  rounded: false,
  push: false,
  square: false,
  glossy: false,
  fab: false,
  fabMini: false,
  padding: '',
  color: '',
  textColor: '',
  noCaps: false,
  noWrap: false,
  dense: false,
  ripple: true,
  tabindex: '',
  align: 'center',
  stack: false,
  stretch: false,
  loading: '',
  disable: false,
  round: false,
  percentage: 0,
  darkPercentage: false,
} as const

export const qBtnSchema: PropSchema[] = [
  { key: 'size', type: 'string', default: '' },
  { key: 'type', type: 'string', default: 'button' },
  { key: 'to', type: 'string', default: '' },
  { key: 'replace', type: 'boolean', default: false },
  { key: 'href', type: 'string', default: '' },
  { key: 'target', type: 'string', default: '' },
  { key: 'label', type: 'string', default: '' },
  { key: 'icon', type: 'string', default: '' },
  { key: 'iconRight', type: 'string', default: '' },
  { key: 'outline', type: 'boolean', default: false },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'unelevated', type: 'boolean', default: false },
  { key: 'rounded', type: 'boolean', default: false },
  { key: 'push', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  { key: 'glossy', type: 'boolean', default: false },
  { key: 'fab', type: 'boolean', default: false },
  { key: 'fabMini', type: 'boolean', default: false },
  { key: 'padding', type: 'string', default: '' },
  { key: 'color', type: 'string', default: '' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'noCaps', type: 'boolean', default: false },
  { key: 'noWrap', type: 'boolean', default: false },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'ripple', type: 'string', default: true },
  { key: 'tabindex', type: 'string', default: '' },
  { key: 'align', type: 'select', default: 'center', options: ['left', 'right', 'center', 'around', 'between', 'evenly'] },
  { key: 'stack', type: 'boolean', default: false },
  { key: 'stretch', type: 'boolean', default: false },
  { key: 'loading', type: 'string', default: '' },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'round', type: 'boolean', default: false },
  { key: 'percentage', type: 'number', default: 0 },
  { key: 'darkPercentage', type: 'boolean', default: false },
]
