// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qBtnDropdownDefaults = {
  transitionShow: 'fade',
  transitionHide: 'fade',
  transitionDuration: '300',
  modelValue: false,
  size: '',
  type: 'button',
  to: '',
  replace: false,
  href: '',
  target: '',
  label: '',
  icon: '',
  iconRight: '',
  outline: false,
  flat: false,
  unelevated: false,
  rounded: false,
  push: false,
  square: false,
  glossy: false,
  fab: false,
  fabMini: false,
  padding: '',
  color: '',
  textColor: '',
  noCaps: false,
  noWrap: false,
  dense: false,
  ripple: true,
  tabindex: '',
  align: 'center',
  stack: false,
  stretch: false,
  loading: '',
  disable: false,
  split: false,
  dropdownIcon: '',
  disableMainBtn: false,
  disableDropdown: false,
  noIconAnimation: false,
  contentStyle: '',
  contentClass: '',
  cover: false,
  persistent: false,
  noEscDismiss: false,
  noRouteDismiss: false,
  autoClose: false,
  noRefocus: false,
  noFocus: false,
  menuAnchor: 'bottom end',
  menuSelf: 'top end',
  menuOffset: '',
  toggleAriaLabel: '',
} as const

export const qBtnDropdownSchema: PropSchema[] = [
  { key: 'transitionShow', type: 'string', default: 'fade' },
  { key: 'transitionHide', type: 'string', default: 'fade' },
  { key: 'transitionDuration', type: 'string', default: '300' },
  { key: 'modelValue', type: 'boolean', default: false },
  { key: 'size', type: 'string', default: '' },
  { key: 'type', type: 'string', default: 'button' },
  { key: 'to', type: 'string', default: '' },
  { key: 'replace', type: 'boolean', default: false },
  { key: 'href', type: 'string', default: '' },
  { key: 'target', type: 'string', default: '' },
  { key: 'label', type: 'string', default: '' },
  { key: 'icon', type: 'string', default: '' },
  { key: 'iconRight', type: 'string', default: '' },
  { key: 'outline', type: 'boolean', default: false },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'unelevated', type: 'boolean', default: false },
  { key: 'rounded', type: 'boolean', default: false },
  { key: 'push', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  { key: 'glossy', type: 'boolean', default: false },
  { key: 'fab', type: 'boolean', default: false },
  { key: 'fabMini', type: 'boolean', default: false },
  { key: 'padding', type: 'string', default: '' },
  { key: 'color', type: 'string', default: '' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'noCaps', type: 'boolean', default: false },
  { key: 'noWrap', type: 'boolean', default: false },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'ripple', type: 'string', default: true },
  { key: 'tabindex', type: 'string', default: '' },
  { key: 'align', type: 'select', default: 'center', options: ['left', 'right', 'center', 'around', 'between', 'evenly'] },
  { key: 'stack', type: 'boolean', default: false },
  { key: 'stretch', type: 'boolean', default: false },
  { key: 'loading', type: 'string', default: '' },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'split', type: 'boolean', default: false },
  { key: 'dropdownIcon', type: 'string', default: '' },
  { key: 'disableMainBtn', type: 'boolean', default: false },
  { key: 'disableDropdown', type: 'boolean', default: false },
  { key: 'noIconAnimation', type: 'boolean', default: false },
  { key: 'contentStyle', type: 'string', default: '' },
  { key: 'contentClass', type: 'string', default: '' },
  { key: 'cover', type: 'boolean', default: false },
  { key: 'persistent', type: 'boolean', default: false },
  { key: 'noEscDismiss', type: 'boolean', default: false },
  { key: 'noRouteDismiss', type: 'boolean', default: false },
  { key: 'autoClose', type: 'boolean', default: false },
  { key: 'noRefocus', type: 'boolean', default: false },
  { key: 'noFocus', type: 'boolean', default: false },
  { key: 'menuAnchor', type: 'select', default: 'bottom end', options: ['top left', 'top middle', 'top right', 'top start', 'top end', 'center left', 'center middle', 'center right', 'center start', 'center end', 'bottom left', 'bottom middle', 'bottom right', 'bottom start', 'bottom end'] },
  { key: 'menuSelf', type: 'select', default: 'top end', options: ['top left', 'top middle', 'top right', 'top start', 'top end', 'center left', 'center middle', 'center right', 'center start', 'center end', 'bottom left', 'bottom middle', 'bottom right', 'bottom start', 'bottom end'] },
  { key: 'menuOffset', type: 'string', default: '' },
  { key: 'toggleAriaLabel', type: 'string', default: '' },
]
