// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qCarouselDefaults = {
  fullscreen: false,
  noRouteFullscreenExit: false,
  modelValue: '',
  keepAlive: false,
  keepAliveInclude: '',
  keepAliveExclude: '',
  keepAliveMax: 0,
  animated: false,
  infinite: false,
  swipeable: false,
  vertical: false,
  transitionPrev: 'fade',
  transitionNext: 'fade',
  transitionDuration: '300',
  dark: '',
  height: '',
  padding: false,
  controlColor: '',
  controlTextColor: '',
  controlType: 'flat',
  autoplay: '',
  arrows: false,
  prevIcon: '',
  nextIcon: '',
  navigation: false,
  navigationPosition: '',
  navigationIcon: '',
  navigationActiveIcon: '',
  thumbnails: false,
} as const

export const qCarouselSchema: PropSchema[] = [
  { key: 'fullscreen', type: 'boolean', default: false },
  { key: 'noRouteFullscreenExit', type: 'boolean', default: false },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'keepAlive', type: 'boolean', default: false },
  { key: 'keepAliveInclude', type: 'string', default: '' },
  { key: 'keepAliveExclude', type: 'string', default: '' },
  { key: 'keepAliveMax', type: 'number', default: 0 },
  { key: 'animated', type: 'boolean', default: false },
  { key: 'infinite', type: 'boolean', default: false },
  { key: 'swipeable', type: 'boolean', default: false },
  { key: 'vertical', type: 'boolean', default: false },
  { key: 'transitionPrev', type: 'string', default: 'fade' },
  { key: 'transitionNext', type: 'string', default: 'fade' },
  { key: 'transitionDuration', type: 'string', default: '300' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'height', type: 'string', default: '' },
  { key: 'padding', type: 'boolean', default: false },
  { key: 'controlColor', type: 'string', default: '' },
  { key: 'controlTextColor', type: 'string', default: '' },
  { key: 'controlType', type: 'select', default: 'flat', options: ['regular', 'flat', 'outline', 'push', 'unelevated'] },
  { key: 'autoplay', type: 'string', default: '' },
  { key: 'arrows', type: 'boolean', default: false },
  { key: 'prevIcon', type: 'string', default: '' },
  { key: 'nextIcon', type: 'string', default: '' },
  { key: 'navigation', type: 'boolean', default: false },
  { key: 'navigationPosition', type: 'select', default: '', options: ['top', 'right', 'bottom', 'left'] },
  { key: 'navigationIcon', type: 'string', default: '' },
  { key: 'navigationActiveIcon', type: 'string', default: '' },
  { key: 'thumbnails', type: 'boolean', default: false },
]
