// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qEditorDefaults = {
  fullscreen: false,
  noRouteFullscreenExit: false,
  modelValue: '',
  readonly: false,
  square: false,
  flat: false,
  dense: false,
  dark: '',
  disable: false,
  minHeight: '10rem',
  maxHeight: '',
  height: '',
  definitions: [] as unknown[],
  fonts: [] as unknown[],
  toolbar: [['left', 'center', 'right', 'justify'], ['bold', 'italic', 'underline', 'strike'], ['undo', 'redo']] as unknown as unknown[][],
  toolbarColor: '',
  toolbarTextColor: '',
  toolbarToggleColor: 'primary',
  toolbarBg: 'grey-3',
  toolbarOutline: false,
  toolbarPush: false,
  toolbarRounded: false,
  paragraphTag: 'div',
  contentStyle: '',
  contentClass: '',
  placeholder: '',
} as const

export const qEditorSchema: PropSchema[] = [
  { key: 'fullscreen', type: 'boolean', default: false },
  { key: 'noRouteFullscreenExit', type: 'boolean', default: false },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'readonly', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'dark', type: 'string', default: '' },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'minHeight', type: 'string', default: '10rem' },
  { key: 'maxHeight', type: 'string', default: '' },
  { key: 'height', type: 'string', default: '' },
  { key: 'definitions', type: 'string', default: '' },
  { key: 'fonts', type: 'string', default: '' },
  { key: 'toolbar', type: 'string', default: '[ [ \'left\', \'center\', \'right\', \'justify\' ], [ \'bold\', \'italic\', \'underline\', \'strike\' ], [ \'undo\', \'redo\' ] ]' },
  { key: 'toolbarColor', type: 'string', default: '' },
  { key: 'toolbarTextColor', type: 'string', default: '' },
  { key: 'toolbarToggleColor', type: 'string', default: 'primary' },
  { key: 'toolbarBg', type: 'string', default: 'grey-3' },
  { key: 'toolbarOutline', type: 'boolean', default: false },
  { key: 'toolbarPush', type: 'boolean', default: false },
  { key: 'toolbarRounded', type: 'boolean', default: false },
  { key: 'paragraphTag', type: 'select', default: 'div', options: ['div', 'p'] },
  { key: 'contentStyle', type: 'string', default: '' },
  { key: 'contentClass', type: 'string', default: '' },
  { key: 'placeholder', type: 'string', default: '' },
]
