// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qExpansionItemDefaults = {
  to: '',
  exact: false,
  replace: false,
  activeClass: 'q-router-link--active',
  exactActiveClass: 'q-router-link--exact-active',
  href: '',
  target: '',
  disable: false,
  modelValue: '',
  icon: '',
  expandIcon: '',
  expandedIcon: '',
  expandIconClass: '',
  toggleAriaLabel: '',
  label: '',
  labelLines: '',
  caption: '',
  captionLines: '',
  dark: '',
  dense: false,
  duration: 300,
  headerInsetLevel: 0,
  contentInsetLevel: 0,
  expandSeparator: false,
  defaultOpened: false,
  hideExpandIcon: false,
  expandIconToggle: false,
  switchToggleSide: false,
  denseToggle: false,
  group: '',
  popup: false,
  headerStyle: '',
  headerClass: '',
} as const

export const qExpansionItemSchema: PropSchema[] = [
  { key: 'to', type: 'string', default: '' },
  { key: 'exact', type: 'boolean', default: false },
  { key: 'replace', type: 'boolean', default: false },
  { key: 'activeClass', type: 'string', default: 'q-router-link--active' },
  { key: 'exactActiveClass', type: 'string', default: 'q-router-link--exact-active' },
  { key: 'href', type: 'string', default: '' },
  { key: 'target', type: 'string', default: '' },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'icon', type: 'string', default: '' },
  { key: 'expandIcon', type: 'string', default: '' },
  { key: 'expandedIcon', type: 'string', default: '' },
  { key: 'expandIconClass', type: 'string', default: '' },
  { key: 'toggleAriaLabel', type: 'string', default: '' },
  { key: 'label', type: 'string', default: '' },
  { key: 'labelLines', type: 'string', default: '' },
  { key: 'caption', type: 'string', default: '' },
  { key: 'captionLines', type: 'string', default: '' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'duration', type: 'number', default: 300 },
  { key: 'headerInsetLevel', type: 'number', default: 0 },
  { key: 'contentInsetLevel', type: 'number', default: 0 },
  { key: 'expandSeparator', type: 'boolean', default: false },
  { key: 'defaultOpened', type: 'boolean', default: false },
  { key: 'hideExpandIcon', type: 'boolean', default: false },
  { key: 'expandIconToggle', type: 'boolean', default: false },
  { key: 'switchToggleSide', type: 'boolean', default: false },
  { key: 'denseToggle', type: 'boolean', default: false },
  { key: 'group', type: 'string', default: '' },
  { key: 'popup', type: 'boolean', default: false },
  { key: 'headerStyle', type: 'string', default: '' },
  { key: 'headerClass', type: 'string', default: '' },
]
