// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qFabDefaults = {
  type: 'a',
  outline: false,
  push: false,
  flat: false,
  unelevated: false,
  padding: '',
  color: '',
  textColor: '',
  glossy: false,
  externalLabel: false,
  label: '',
  labelPosition: 'right',
  hideLabel: '',
  labelClass: '',
  labelStyle: '',
  square: false,
  disable: false,
  tabindex: '',
  modelValue: '',
  icon: '',
  activeIcon: '',
  hideIcon: false,
  direction: 'right',
  verticalActionsAlign: 'center',
  persistent: false,
} as const

export const qFabSchema: PropSchema[] = [
  { key: 'type', type: 'select', default: 'a', options: ['a', 'submit', 'button', 'reset'] },
  { key: 'outline', type: 'boolean', default: false },
  { key: 'push', type: 'boolean', default: false },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'unelevated', type: 'boolean', default: false },
  { key: 'padding', type: 'string', default: '' },
  { key: 'color', type: 'string', default: '' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'glossy', type: 'boolean', default: false },
  { key: 'externalLabel', type: 'boolean', default: false },
  { key: 'label', type: 'string', default: '' },
  { key: 'labelPosition', type: 'select', default: 'right', options: ['top', 'right', 'bottom', 'left'] },
  { key: 'hideLabel', type: 'string', default: '' },
  { key: 'labelClass', type: 'string', default: '' },
  { key: 'labelStyle', type: 'string', default: '' },
  { key: 'square', type: 'boolean', default: false },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'tabindex', type: 'string', default: '' },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'icon', type: 'string', default: '' },
  { key: 'activeIcon', type: 'string', default: '' },
  { key: 'hideIcon', type: 'boolean', default: false },
  { key: 'direction', type: 'select', default: 'right', options: ['up', 'right', 'down', 'left'] },
  { key: 'verticalActionsAlign', type: 'select', default: 'center', options: ['left', 'center', 'right'] },
  { key: 'persistent', type: 'boolean', default: false },
]
