// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qImgDefaults = {
  ratio: '',
  src: '',
  srcset: '',
  sizes: '',
  placeholderSrc: '',
  errorSrc: '',
  initialRatio: '1.7778',
  width: '',
  height: '',
  loading: 'lazy',
  loadingShowDelay: '0',
  crossorigin: '',
  decoding: '',
  referrerpolicy: '',
  fetchpriority: 'auto',
  fit: 'cover',
  position: '50% 50%',
  alt: '',
  draggable: false,
  imgClass: '',
  imgStyle: '',
  spinnerColor: '',
  spinnerSize: '',
  noSpinner: false,
  noNativeMenu: false,
  noTransition: false,
} as const

export const qImgSchema: PropSchema[] = [
  { key: 'ratio', type: 'string', default: '' },
  { key: 'src', type: 'string', default: '' },
  { key: 'srcset', type: 'string', default: '' },
  { key: 'sizes', type: 'string', default: '' },
  { key: 'placeholderSrc', type: 'string', default: '' },
  { key: 'errorSrc', type: 'string', default: '' },
  { key: 'initialRatio', type: 'string', default: '1.7778' },
  { key: 'width', type: 'string', default: '' },
  { key: 'height', type: 'string', default: '' },
  { key: 'loading', type: 'select', default: 'lazy', options: ['lazy', 'eager'] },
  { key: 'loadingShowDelay', type: 'string', default: '0' },
  { key: 'crossorigin', type: 'select', default: '', options: ['anonymous', 'use-credentials'] },
  { key: 'decoding', type: 'select', default: '', options: ['sync', 'async', 'auto'] },
  { key: 'referrerpolicy', type: 'select', default: '', options: ['no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', 'same-origin', 'strict-origin', 'strict-origin-when-cross-origin', 'unsafe-url'] },
  { key: 'fetchpriority', type: 'select', default: 'auto', options: ['high', 'low', 'auto'] },
  { key: 'fit', type: 'select', default: 'cover', options: ['cover', 'fill', 'contain', 'none', 'scale-down'] },
  { key: 'position', type: 'string', default: '50% 50%' },
  { key: 'alt', type: 'string', default: '' },
  { key: 'draggable', type: 'boolean', default: false },
  { key: 'imgClass', type: 'string', default: '' },
  { key: 'imgStyle', type: 'string', default: '' },
  { key: 'spinnerColor', type: 'string', default: '' },
  { key: 'spinnerSize', type: 'string', default: '' },
  { key: 'noSpinner', type: 'boolean', default: false },
  { key: 'noNativeMenu', type: 'boolean', default: false },
  { key: 'noTransition', type: 'boolean', default: false },
]
