// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qInputDefaults = {
  name: '',
  mask: '',
  fillMask: '',
  reverseFillMask: false,
  unmaskedValue: false,
  modelValue: '',
  error: '',
  errorMessage: '',
  noErrorIcon: false,
  rules: '',
  reactiveRules: false,
  lazyRules: false,
  label: '',
  stackLabel: false,
  hint: '',
  hideHint: false,
  prefix: '',
  suffix: '',
  labelColor: '',
  color: '',
  bgColor: '',
  dark: '',
  loading: false,
  clearable: false,
  clearIcon: '',
  filled: false,
  outlined: false,
  borderless: false,
  standout: '',
  labelSlot: false,
  bottomSlots: false,
  hideBottomSpace: false,
  counter: false,
  rounded: false,
  square: false,
  dense: false,
  itemAligned: false,
  disable: false,
  readonly: false,
  autofocus: false,
  for: '',
  shadowText: '',
  type: 'text',
  debounce: '',
  maxlength: '',
  autogrow: false,
  inputClass: '',
  inputStyle: ''
} as const

export const qInputSchema: PropSchema[] = [
  { key: 'name', type: 'string', default: '' },
  { key: 'mask', type: 'string', default: '' },
  { key: 'fillMask', type: 'string', default: '' },
  { key: 'reverseFillMask', type: 'boolean', default: false },
  { key: 'unmaskedValue', type: 'boolean', default: false },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'error', type: 'string', default: '' },
  { key: 'errorMessage', type: 'string', default: '' },
  { key: 'noErrorIcon', type: 'boolean', default: false },
  { key: 'rules', type: 'string', default: '' },
  { key: 'reactiveRules', type: 'boolean', default: false },
  {
    key: 'lazyRules',
    type: 'select',
    default: false,
    options: ['true', 'false', 'ondemand']
  },
  { key: 'label', type: 'string', default: '' },
  { key: 'stackLabel', type: 'boolean', default: false },
  { key: 'hint', type: 'string', default: '' },
  { key: 'hideHint', type: 'boolean', default: false },
  { key: 'prefix', type: 'string', default: '' },
  { key: 'suffix', type: 'string', default: '' },
  { key: 'labelColor', type: 'string', default: '' },
  { key: 'color', type: 'string', default: '' },
  { key: 'bgColor', type: 'string', default: '' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'loading', type: 'boolean', default: false },
  { key: 'clearable', type: 'boolean', default: false },
  { key: 'clearIcon', type: 'string', default: '' },
  { key: 'filled', type: 'boolean', default: false },
  { key: 'outlined', type: 'boolean', default: false },
  { key: 'borderless', type: 'boolean', default: false },
  { key: 'standout', type: 'string', default: '' },
  { key: 'labelSlot', type: 'boolean', default: false },
  { key: 'bottomSlots', type: 'boolean', default: false },
  { key: 'hideBottomSpace', type: 'boolean', default: false },
  { key: 'counter', type: 'boolean', default: false },
  { key: 'rounded', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'itemAligned', type: 'boolean', default: false },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'readonly', type: 'boolean', default: false },
  { key: 'autofocus', type: 'boolean', default: false },
  { key: 'for', type: 'string', default: '' },
  { key: 'shadowText', type: 'string', default: '' },
  {
    key: 'type',
    type: 'select',
    default: 'text',
    options: [
      'text',
      'password',
      'textarea',
      'email',
      'search',
      'tel',
      'file',
      'number',
      'url',
      'time',
      'date',
      'datetime-local'
    ]
  },
  { key: 'debounce', type: 'string', default: '' },
  { key: 'maxlength', type: 'string', default: '' },
  { key: 'autogrow', type: 'boolean', default: false },
  { key: 'inputClass', type: 'string', default: '' },
  { key: 'inputStyle', type: 'string', default: '' }
]
