// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qMenuDefaults = {
  transitionShow: 'fade',
  transitionHide: 'fade',
  transitionDuration: '300',
  target: true,
  noParentEvent: false,
  contextMenu: false,
  modelValue: '',
  dark: '',
  fit: false,
  cover: false,
  anchor: '',
  self: '',
  offset: '',
  scrollTarget: '',
  touchPosition: false,
  persistent: false,
  noEscDismiss: false,
  noRouteDismiss: false,
  autoClose: false,
  separateClosePopup: false,
  square: false,
  noRefocus: false,
  noFocus: false,
  maxHeight: '',
  maxWidth: '',
} as const

export const qMenuSchema: PropSchema[] = [
  { key: 'transitionShow', type: 'string', default: 'fade' },
  { key: 'transitionHide', type: 'string', default: 'fade' },
  { key: 'transitionDuration', type: 'string', default: '300' },
  { key: 'target', type: 'string', default: true },
  { key: 'noParentEvent', type: 'boolean', default: false },
  { key: 'contextMenu', type: 'boolean', default: false },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'fit', type: 'boolean', default: false },
  { key: 'cover', type: 'boolean', default: false },
  { key: 'anchor', type: 'select', default: '', options: ['top left', 'top middle', 'top right', 'top start', 'top end', 'center left', 'center middle', 'center right', 'center start', 'center end', 'bottom left', 'bottom middle', 'bottom right', 'bottom start', 'bottom end'] },
  { key: 'self', type: 'select', default: '', options: ['top left', 'top middle', 'top right', 'top start', 'top end', 'center left', 'center middle', 'center right', 'center start', 'center end', 'bottom left', 'bottom middle', 'bottom right', 'bottom start', 'bottom end'] },
  { key: 'offset', type: 'string', default: '' },
  { key: 'scrollTarget', type: 'string', default: '' },
  { key: 'touchPosition', type: 'boolean', default: false },
  { key: 'persistent', type: 'boolean', default: false },
  { key: 'noEscDismiss', type: 'boolean', default: false },
  { key: 'noRouteDismiss', type: 'boolean', default: false },
  { key: 'autoClose', type: 'boolean', default: false },
  { key: 'separateClosePopup', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  { key: 'noRefocus', type: 'boolean', default: false },
  { key: 'noFocus', type: 'boolean', default: false },
  { key: 'maxHeight', type: 'string', default: '' },
  { key: 'maxWidth', type: 'string', default: '' },
]
