// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qPaginationDefaults = {
  modelValue: 0,
  min: '1',
  max: '',
  dark: '',
  size: '',
  disable: false,
  input: false,
  iconPrev: '',
  iconNext: '',
  iconFirst: '',
  iconLast: '',
  toFn: '',
  boundaryLinks: '',
  boundaryNumbers: '',
  directionLinks: '',
  ellipses: '',
  maxPages: '0',
  flat: false,
  outline: false,
  unelevated: false,
  push: false,
  color: 'primary',
  textColor: '',
  activeDesign: '',
  activeColor: 'primary',
  activeTextColor: '',
  round: false,
  rounded: false,
  glossy: false,
  gutter: '2px',
  padding: '3px 2px',
  inputStyle: '',
  inputClass: '',
  ripple: true,
} as const

export const qPaginationSchema: PropSchema[] = [
  { key: 'modelValue', type: 'number', default: 0 },
  { key: 'min', type: 'string', default: '1' },
  { key: 'max', type: 'string', default: '' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'size', type: 'string', default: '' },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'input', type: 'boolean', default: false },
  { key: 'iconPrev', type: 'string', default: '' },
  { key: 'iconNext', type: 'string', default: '' },
  { key: 'iconFirst', type: 'string', default: '' },
  { key: 'iconLast', type: 'string', default: '' },
  { key: 'toFn', type: 'string', default: '' },
  { key: 'boundaryLinks', type: 'string', default: '' },
  { key: 'boundaryNumbers', type: 'string', default: '' },
  { key: 'directionLinks', type: 'string', default: '' },
  { key: 'ellipses', type: 'string', default: '' },
  { key: 'maxPages', type: 'string', default: '0' },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'outline', type: 'boolean', default: false },
  { key: 'unelevated', type: 'boolean', default: false },
  { key: 'push', type: 'boolean', default: false },
  { key: 'color', type: 'string', default: 'primary' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'activeDesign', type: 'select', default: '', options: ['flat', 'outline', 'push', 'unelevated', ''] },
  { key: 'activeColor', type: 'string', default: 'primary' },
  { key: 'activeTextColor', type: 'string', default: '' },
  { key: 'round', type: 'boolean', default: false },
  { key: 'rounded', type: 'boolean', default: false },
  { key: 'glossy', type: 'boolean', default: false },
  { key: 'gutter', type: 'string', default: '2px' },
  { key: 'padding', type: 'string', default: '3px 2px' },
  { key: 'inputStyle', type: 'string', default: '' },
  { key: 'inputClass', type: 'string', default: '' },
  { key: 'ripple', type: 'string', default: true },
]
