// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qRangeDefaults = {
  name: '',
  min: 0,
  max: 100,
  innerMin: 0,
  innerMax: 0,
  step: 1,
  snap: false,
  reverse: false,
  vertical: false,
  color: '',
  trackColor: '',
  trackImg: '',
  innerTrackColor: '',
  innerTrackImg: '',
  selectionColor: '',
  selectionImg: '',
  label: false,
  labelColor: '',
  labelTextColor: '',
  switchLabelSide: false,
  labelAlways: false,
  markers: '',
  markerLabels: '',
  markerLabelsClass: '',
  switchMarkerLabelsSide: false,
  trackSize: '4px',
  thumbSize: '20px',
  thumbColor: '',
  thumbPath: 'M 4, 10 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0',
  dark: '',
  dense: false,
  disable: false,
  readonly: false,
  tabindex: '',
  modelValue: { min: null, max: null },
  dragRange: false,
  dragOnlyRange: false,
  leftLabelColor: '',
  leftLabelTextColor: '',
  rightLabelColor: '',
  rightLabelTextColor: '',
  leftLabelValue: '',
  rightLabelValue: '',
  leftThumbColor: '',
  rightThumbColor: ''
} as const

export const qRangeSchema: PropSchema[] = [
  { key: 'name', type: 'string', default: '' },
  { key: 'min', type: 'number', default: 0 },
  { key: 'max', type: 'number', default: 100 },
  { key: 'innerMin', type: 'number', default: 0 },
  { key: 'innerMax', type: 'number', default: 0 },
  { key: 'step', type: 'number', default: 1 },
  { key: 'snap', type: 'boolean', default: false },
  { key: 'reverse', type: 'boolean', default: false },
  { key: 'vertical', type: 'boolean', default: false },
  { key: 'color', type: 'string', default: '' },
  { key: 'trackColor', type: 'string', default: '' },
  { key: 'trackImg', type: 'string', default: '' },
  { key: 'innerTrackColor', type: 'string', default: '' },
  { key: 'innerTrackImg', type: 'string', default: '' },
  { key: 'selectionColor', type: 'string', default: '' },
  { key: 'selectionImg', type: 'string', default: '' },
  { key: 'label', type: 'boolean', default: false },
  { key: 'labelColor', type: 'string', default: '' },
  { key: 'labelTextColor', type: 'string', default: '' },
  { key: 'switchLabelSide', type: 'boolean', default: false },
  { key: 'labelAlways', type: 'boolean', default: false },
  { key: 'markers', type: 'string', default: '' },
  { key: 'markerLabels', type: 'string', default: '' },
  { key: 'markerLabelsClass', type: 'string', default: '' },
  { key: 'switchMarkerLabelsSide', type: 'boolean', default: false },
  { key: 'trackSize', type: 'string', default: '4px' },
  { key: 'thumbSize', type: 'string', default: '20px' },
  { key: 'thumbColor', type: 'string', default: '' },
  {
    key: 'thumbPath',
    type: 'string',
    default: 'M 4, 10 a 6,6 0 1,0 12,0 a 6,6 0 1,0 -12,0'
  },
  { key: 'dark', type: 'string', default: '' },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'readonly', type: 'boolean', default: false },
  { key: 'tabindex', type: 'string', default: '' },
  { key: 'modelValue', type: 'string', default: { min: null, max: null } },
  { key: 'dragRange', type: 'boolean', default: false },
  { key: 'dragOnlyRange', type: 'boolean', default: false },
  { key: 'leftLabelColor', type: 'string', default: '' },
  { key: 'leftLabelTextColor', type: 'string', default: '' },
  { key: 'rightLabelColor', type: 'string', default: '' },
  { key: 'rightLabelTextColor', type: 'string', default: '' },
  { key: 'leftLabelValue', type: 'string', default: '' },
  { key: 'rightLabelValue', type: 'string', default: '' },
  { key: 'leftThumbColor', type: 'string', default: '' },
  { key: 'rightThumbColor', type: 'string', default: '' }
]
