// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qSelectDefaults = {
  name: '',
  virtualScrollHorizontal: false,
  virtualScrollSliceSize: '10',
  virtualScrollSliceRatioBefore: '1',
  virtualScrollSliceRatioAfter: '1',
  virtualScrollItemSize: '24',
  virtualScrollStickySizeStart: '0',
  virtualScrollStickySizeEnd: '0',
  tableColspan: '',
  modelValue: '',
  error: '',
  errorMessage: '',
  noErrorIcon: false,
  rules: '',
  reactiveRules: false,
  lazyRules: false,
  label: '',
  stackLabel: false,
  hint: '',
  hideHint: false,
  prefix: '',
  suffix: '',
  labelColor: '',
  color: '',
  bgColor: '',
  dark: '',
  loading: false,
  clearable: false,
  clearIcon: '',
  filled: false,
  outlined: false,
  borderless: false,
  standout: '',
  labelSlot: false,
  bottomSlots: false,
  hideBottomSpace: false,
  counter: false,
  rounded: false,
  square: false,
  dense: false,
  itemAligned: false,
  disable: false,
  readonly: false,
  autofocus: false,
  for: '',
  multiple: false,
  displayValue: '',
  displayValueHtml: false,
  options: [],
  optionValue: 'value',
  optionLabel: 'label',
  optionDisable: 'disable',
  hideSelected: false,
  hideDropdownIcon: false,
  dropdownIcon: '',
  maxValues: '',
  optionsDense: false,
  optionsDark: '',
  optionsSelectedClass: '',
  optionsHtml: false,
  optionsCover: false,
  menuShrink: false,
  menuAnchor: '',
  menuSelf: '',
  menuOffset: '',
  popupContentClass: '',
  popupContentStyle: '',
  popupNoRouteDismiss: false,
  useChips: false,
  useInput: false,
  maxlength: '',
  fillInput: false,
  newValueMode: '',
  mapOptions: false,
  disableTabSelection: false,
  emitValue: false,
  inputDebounce: '500',
  inputClass: '',
  inputStyle: '',
  tabindex: '0',
  autocomplete: '',
  transitionShow: 'fade',
  transitionHide: 'fade',
  transitionDuration: '300',
  behavior: 'default',
} as const

export const qSelectSchema: PropSchema[] = [
  { key: 'name', type: 'string', default: '' },
  { key: 'virtualScrollHorizontal', type: 'boolean', default: false },
  { key: 'virtualScrollSliceSize', type: 'string', default: '10' },
  { key: 'virtualScrollSliceRatioBefore', type: 'string', default: '1' },
  { key: 'virtualScrollSliceRatioAfter', type: 'string', default: '1' },
  { key: 'virtualScrollItemSize', type: 'string', default: '24' },
  { key: 'virtualScrollStickySizeStart', type: 'string', default: '0' },
  { key: 'virtualScrollStickySizeEnd', type: 'string', default: '0' },
  { key: 'tableColspan', type: 'string', default: '' },
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'error', type: 'string', default: '' },
  { key: 'errorMessage', type: 'string', default: '' },
  { key: 'noErrorIcon', type: 'boolean', default: false },
  { key: 'rules', type: 'string', default: '' },
  { key: 'reactiveRules', type: 'boolean', default: false },
  { key: 'lazyRules', type: 'select', default: false, options: ['true', 'false', 'ondemand'] },
  { key: 'label', type: 'string', default: '' },
  { key: 'stackLabel', type: 'boolean', default: false },
  { key: 'hint', type: 'string', default: '' },
  { key: 'hideHint', type: 'boolean', default: false },
  { key: 'prefix', type: 'string', default: '' },
  { key: 'suffix', type: 'string', default: '' },
  { key: 'labelColor', type: 'string', default: '' },
  { key: 'color', type: 'string', default: '' },
  { key: 'bgColor', type: 'string', default: '' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'loading', type: 'boolean', default: false },
  { key: 'clearable', type: 'boolean', default: false },
  { key: 'clearIcon', type: 'string', default: '' },
  { key: 'filled', type: 'boolean', default: false },
  { key: 'outlined', type: 'boolean', default: false },
  { key: 'borderless', type: 'boolean', default: false },
  { key: 'standout', type: 'string', default: '' },
  { key: 'labelSlot', type: 'boolean', default: false },
  { key: 'bottomSlots', type: 'boolean', default: false },
  { key: 'hideBottomSpace', type: 'boolean', default: false },
  { key: 'counter', type: 'boolean', default: false },
  { key: 'rounded', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'itemAligned', type: 'boolean', default: false },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'readonly', type: 'boolean', default: false },
  { key: 'autofocus', type: 'boolean', default: false },
  { key: 'for', type: 'string', default: '' },
  { key: 'multiple', type: 'boolean', default: false },
  { key: 'displayValue', type: 'string', default: '' },
  { key: 'displayValueHtml', type: 'boolean', default: false },
  { key: 'options', type: 'string', default: [] },
  { key: 'optionValue', type: 'string', default: 'value' },
  { key: 'optionLabel', type: 'string', default: 'label' },
  { key: 'optionDisable', type: 'string', default: 'disable' },
  { key: 'hideSelected', type: 'boolean', default: false },
  { key: 'hideDropdownIcon', type: 'boolean', default: false },
  { key: 'dropdownIcon', type: 'string', default: '' },
  { key: 'maxValues', type: 'string', default: '' },
  { key: 'optionsDense', type: 'boolean', default: false },
  { key: 'optionsDark', type: 'string', default: '' },
  { key: 'optionsSelectedClass', type: 'string', default: '' },
  { key: 'optionsHtml', type: 'boolean', default: false },
  { key: 'optionsCover', type: 'boolean', default: false },
  { key: 'menuShrink', type: 'boolean', default: false },
  { key: 'menuAnchor', type: 'select', default: '', options: ['top left', 'top middle', 'top right', 'top start', 'top end', 'center left', 'center middle', 'center right', 'center start', 'center end', 'bottom left', 'bottom middle', 'bottom right', 'bottom start', 'bottom end'] },
  { key: 'menuSelf', type: 'select', default: '', options: ['top left', 'top middle', 'top right', 'top start', 'top end', 'center left', 'center middle', 'center right', 'center start', 'center end', 'bottom left', 'bottom middle', 'bottom right', 'bottom start', 'bottom end'] },
  { key: 'menuOffset', type: 'string', default: '' },
  { key: 'popupContentClass', type: 'string', default: '' },
  { key: 'popupContentStyle', type: 'string', default: '' },
  { key: 'popupNoRouteDismiss', type: 'boolean', default: false },
  { key: 'useChips', type: 'boolean', default: false },
  { key: 'useInput', type: 'boolean', default: false },
  { key: 'maxlength', type: 'string', default: '' },
  { key: 'fillInput', type: 'boolean', default: false },
  { key: 'newValueMode', type: 'select', default: '', options: ['add', 'add-unique', 'toggle'] },
  { key: 'mapOptions', type: 'boolean', default: false },
  { key: 'disableTabSelection', type: 'boolean', default: false },
  { key: 'emitValue', type: 'boolean', default: false },
  { key: 'inputDebounce', type: 'string', default: '500' },
  { key: 'inputClass', type: 'string', default: '' },
  { key: 'inputStyle', type: 'string', default: '' },
  { key: 'tabindex', type: 'string', default: '0' },
  { key: 'autocomplete', type: 'string', default: '' },
  { key: 'transitionShow', type: 'string', default: 'fade' },
  { key: 'transitionHide', type: 'string', default: 'fade' },
  { key: 'transitionDuration', type: 'string', default: '300' },
  { key: 'behavior', type: 'select', default: 'default', options: ['default', 'menu', 'dialog'] },
]
