// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-dev/tools generate:props

import type { PropSchema } from '../../types/props'

export const qStepperDefaults = {
  modelValue: '',
  keepAlive: false,
  keepAliveInclude: '',
  keepAliveExclude: '',
  keepAliveMax: 0,
  animated: false,
  infinite: false,
  swipeable: false,
  vertical: false,
  transitionPrev: '# slide-right/slide-down',
  transitionNext: '# slide-left/slide-up',
  transitionDuration: '300',
  dark: '',
  flat: false,
  bordered: false,
  alternativeLabels: false,
  headerNav: false,
  contracted: false,
  inactiveIcon: '',
  inactiveColor: '',
  doneIcon: '',
  doneColor: '',
  activeIcon: '',
  activeColor: '',
  errorIcon: '',
  errorColor: '',
  headerClass: '',
} as const

export const qStepperSchema: PropSchema[] = [
  { key: 'modelValue', type: 'string', default: '' },
  { key: 'keepAlive', type: 'boolean', default: false },
  { key: 'keepAliveInclude', type: 'string', default: '' },
  { key: 'keepAliveExclude', type: 'string', default: '' },
  { key: 'keepAliveMax', type: 'number', default: 0 },
  { key: 'animated', type: 'boolean', default: false },
  { key: 'infinite', type: 'boolean', default: false },
  { key: 'swipeable', type: 'boolean', default: false },
  { key: 'vertical', type: 'boolean', default: false },
  { key: 'transitionPrev', type: 'string', default: '# slide-right/slide-down' },
  { key: 'transitionNext', type: 'string', default: '# slide-left/slide-up' },
  { key: 'transitionDuration', type: 'string', default: '300' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'bordered', type: 'boolean', default: false },
  { key: 'alternativeLabels', type: 'boolean', default: false },
  { key: 'headerNav', type: 'boolean', default: false },
  { key: 'contracted', type: 'boolean', default: false },
  { key: 'inactiveIcon', type: 'string', default: '' },
  { key: 'inactiveColor', type: 'string', default: '' },
  { key: 'doneIcon', type: 'string', default: '' },
  { key: 'doneColor', type: 'string', default: '' },
  { key: 'activeIcon', type: 'string', default: '' },
  { key: 'activeColor', type: 'string', default: '' },
  { key: 'errorIcon', type: 'string', default: '' },
  { key: 'errorColor', type: 'string', default: '' },
  { key: 'headerClass', type: 'string', default: '' },
]
