// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qTableDefaults = {
  fullscreen: false,
  noRouteFullscreenExit: false,
  rows: '',
  rowKey: 'id',
  virtualScroll: false,
  virtualScrollTarget: '',
  virtualScrollSliceSize: '10',
  virtualScrollSliceRatioBefore: '1',
  virtualScrollSliceRatioAfter: '1',
  virtualScrollItemSize: '',
  virtualScrollStickySizeStart: '0',
  virtualScrollStickySizeEnd: '0',
  tableColspan: '',
  color: 'grey-8',
  iconFirstPage: '',
  iconPrevPage: '',
  iconNextPage: '',
  iconLastPage: '',
  grid: false,
  gridHeader: false,
  dense: false,
  columns: '',
  visibleColumns: '',
  loading: false,
  title: '',
  hideHeader: false,
  hideBottom: false,
  hideSelectedBanner: false,
  hideNoData: false,
  hidePagination: false,
  dark: '',
  flat: false,
  bordered: false,
  square: false,
  separator: 'horizontal',
  wrapCells: false,
  binaryStateSort: false,
  columnSortOrder: 'ad',
  noDataLabel: '',
  noResultsLabel: '',
  loadingLabel: '',
  selectedRowsLabel: '',
  rowsPerPageLabel: '',
  paginationLabel: '',
  tableStyle: '',
  tableClass: '',
  tableHeaderStyle: '',
  tableHeaderClass: '',
  tableRowStyleFn: '',
  tableRowClassFn: '',
  cardContainerStyle: '',
  cardContainerClass: '',
  cardStyle: '',
  cardClass: '',
  cardStyleFn: '',
  cardClassFn: '',
  titleClass: '',
  filter: '',
  filterMethod: '',
  pagination: '',
  rowsPerPageOptions: [5, 7, 10, 15, 20, 25, 50, 0],
  selection: 'none',
  selected: [],
  expanded: '',
  sortMethod: ''
} as const

export const qTableSchema: PropSchema[] = [
  { key: 'fullscreen', type: 'boolean', default: false },
  { key: 'noRouteFullscreenExit', type: 'boolean', default: false },
  { key: 'rows', type: 'string', default: '' },
  { key: 'rowKey', type: 'string', default: 'id' },
  { key: 'virtualScroll', type: 'boolean', default: false },
  { key: 'virtualScrollTarget', type: 'string', default: '' },
  { key: 'virtualScrollSliceSize', type: 'string', default: '10' },
  { key: 'virtualScrollSliceRatioBefore', type: 'string', default: '1' },
  { key: 'virtualScrollSliceRatioAfter', type: 'string', default: '1' },
  { key: 'virtualScrollItemSize', type: 'string', default: '' },
  { key: 'virtualScrollStickySizeStart', type: 'string', default: '0' },
  { key: 'virtualScrollStickySizeEnd', type: 'string', default: '0' },
  { key: 'tableColspan', type: 'string', default: '' },
  { key: 'color', type: 'string', default: 'grey-8' },
  { key: 'iconFirstPage', type: 'string', default: '' },
  { key: 'iconPrevPage', type: 'string', default: '' },
  { key: 'iconNextPage', type: 'string', default: '' },
  { key: 'iconLastPage', type: 'string', default: '' },
  { key: 'grid', type: 'boolean', default: false },
  { key: 'gridHeader', type: 'boolean', default: false },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'columns', type: 'string', default: '' },
  { key: 'visibleColumns', type: 'string', default: '' },
  { key: 'loading', type: 'boolean', default: false },
  { key: 'title', type: 'string', default: '' },
  { key: 'hideHeader', type: 'boolean', default: false },
  { key: 'hideBottom', type: 'boolean', default: false },
  { key: 'hideSelectedBanner', type: 'boolean', default: false },
  { key: 'hideNoData', type: 'boolean', default: false },
  { key: 'hidePagination', type: 'boolean', default: false },
  { key: 'dark', type: 'string', default: '' },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'bordered', type: 'boolean', default: false },
  { key: 'square', type: 'boolean', default: false },
  {
    key: 'separator',
    type: 'select',
    default: 'horizontal',
    options: ['horizontal', 'vertical', 'cell', 'none']
  },
  { key: 'wrapCells', type: 'boolean', default: false },
  { key: 'binaryStateSort', type: 'boolean', default: false },
  {
    key: 'columnSortOrder',
    type: 'select',
    default: 'ad',
    options: ['ad', 'da']
  },
  { key: 'noDataLabel', type: 'string', default: '' },
  { key: 'noResultsLabel', type: 'string', default: '' },
  { key: 'loadingLabel', type: 'string', default: '' },
  { key: 'selectedRowsLabel', type: 'string', default: '' },
  { key: 'rowsPerPageLabel', type: 'string', default: '' },
  { key: 'paginationLabel', type: 'string', default: '' },
  { key: 'tableStyle', type: 'string', default: '' },
  { key: 'tableClass', type: 'string', default: '' },
  { key: 'tableHeaderStyle', type: 'string', default: '' },
  { key: 'tableHeaderClass', type: 'string', default: '' },
  { key: 'tableRowStyleFn', type: 'string', default: '' },
  { key: 'tableRowClassFn', type: 'string', default: '' },
  { key: 'cardContainerStyle', type: 'string', default: '' },
  { key: 'cardContainerClass', type: 'string', default: '' },
  { key: 'cardStyle', type: 'string', default: '' },
  { key: 'cardClass', type: 'string', default: '' },
  { key: 'cardStyleFn', type: 'string', default: '' },
  { key: 'cardClassFn', type: 'string', default: '' },
  { key: 'titleClass', type: 'string', default: '' },
  { key: 'filter', type: 'string', default: '' },
  { key: 'filterMethod', type: 'string', default: '' },
  { key: 'pagination', type: 'string', default: '' },
  {
    key: 'rowsPerPageOptions',
    type: 'string',
    default: [5, 7, 10, 15, 20, 25, 50, 0]
  },
  {
    key: 'selection',
    type: 'select',
    default: 'none',
    options: ['single', 'multiple', 'none']
  },
  { key: 'selected', type: 'string', default: [] },
  { key: 'expanded', type: 'string', default: '' },
  { key: 'sortMethod', type: 'string', default: '' }
]
