// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qTreeDefaults = {
  nodes: '',
  nodeKey: 'label',
  labelKey: 'label',
  childrenKey: 'children',
  noConnectors: false,
  color: '',
  controlColor: '',
  textColor: '',
  selectedColor: '',
  dense: false,
  dark: '',
  icon: '',
  tickStrategy: 'none',
  ticked: '',
  expanded: '',
  selected: '',
  noSelectionUnset: false,
  defaultExpandAll: false,
  accordion: false,
  noTransition: false,
  filter: '',
  filterMethod: '',
  duration: 300,
  noNodesLabel: '',
  noResultsLabel: '',
} as const

export const qTreeSchema: PropSchema[] = [
  { key: 'nodes', type: 'string', default: '' },
  { key: 'nodeKey', type: 'string', default: '' },
  { key: 'labelKey', type: 'string', default: 'label' },
  { key: 'childrenKey', type: 'string', default: 'children' },
  { key: 'noConnectors', type: 'boolean', default: false },
  { key: 'color', type: 'string', default: '' },
  { key: 'controlColor', type: 'string', default: '' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'selectedColor', type: 'string', default: '' },
  { key: 'dense', type: 'boolean', default: false },
  { key: 'dark', type: 'string', default: '' },
  { key: 'icon', type: 'string', default: '' },
  { key: 'tickStrategy', type: 'select', default: 'none', options: ['none', 'strict', 'leaf', 'leaf-filtered'] },
  { key: 'ticked', type: 'string', default: '' },
  { key: 'expanded', type: 'string', default: '' },
  { key: 'selected', type: 'string', default: '' },
  { key: 'noSelectionUnset', type: 'boolean', default: false },
  { key: 'defaultExpandAll', type: 'boolean', default: false },
  { key: 'accordion', type: 'boolean', default: false },
  { key: 'noTransition', type: 'boolean', default: false },
  { key: 'filter', type: 'string', default: '' },
  { key: 'filterMethod', type: 'string', default: '' },
  { key: 'duration', type: 'number', default: 300 },
  { key: 'noNodesLabel', type: 'string', default: '' },
  { key: 'noResultsLabel', type: 'string', default: '' },
]
