// AUTO-GENERATED from Quasar docs JSON. Do not edit by hand.
// Regenerate with: pnpm --filter @quasar-testing-harness/tools generate:props

import type { PropSchema } from '../../types/props'

export const qUploaderDefaults = {
  factory: '',
  url: '',
  method: 'POST',
  fieldName: 'file => file.name',
  headers: '',
  formFields: '',
  withCredentials: '',
  sendRaw: '',
  batch: '',
  multiple: false,
  accept: '',
  capture: '',
  maxFileSize: '',
  maxTotalSize: '',
  maxFiles: '',
  filter: '',
  label: '',
  color: '',
  textColor: '',
  dark: '',
  square: false,
  flat: false,
  bordered: false,
  noThumbnails: false,
  autoUpload: false,
  hideUploadBtn: false,
  thumbnailFit: 'cover',
  disable: false,
  readonly: false,
} as const

export const qUploaderSchema: PropSchema[] = [
  { key: 'factory', type: 'string', default: '' },
  { key: 'url', type: 'string', default: '' },
  { key: 'method', type: 'select', default: 'POST', options: ['POST', 'PUT'] },
  { key: 'fieldName', type: 'string', default: 'file => file.name' },
  { key: 'headers', type: 'string', default: '' },
  { key: 'formFields', type: 'string', default: '' },
  { key: 'withCredentials', type: 'string', default: '' },
  { key: 'sendRaw', type: 'string', default: '' },
  { key: 'batch', type: 'string', default: '' },
  { key: 'multiple', type: 'boolean', default: false },
  { key: 'accept', type: 'string', default: '' },
  { key: 'capture', type: 'select', default: '', options: ['user', 'environment'] },
  { key: 'maxFileSize', type: 'string', default: '' },
  { key: 'maxTotalSize', type: 'string', default: '' },
  { key: 'maxFiles', type: 'string', default: '' },
  { key: 'filter', type: 'string', default: '' },
  { key: 'label', type: 'string', default: '' },
  { key: 'color', type: 'string', default: '' },
  { key: 'textColor', type: 'string', default: '' },
  { key: 'dark', type: 'string', default: '' },
  { key: 'square', type: 'boolean', default: false },
  { key: 'flat', type: 'boolean', default: false },
  { key: 'bordered', type: 'boolean', default: false },
  { key: 'noThumbnails', type: 'boolean', default: false },
  { key: 'autoUpload', type: 'boolean', default: false },
  { key: 'hideUploadBtn', type: 'boolean', default: false },
  { key: 'thumbnailFit', type: 'string', default: 'cover' },
  { key: 'disable', type: 'boolean', default: false },
  { key: 'readonly', type: 'boolean', default: false },
]
